#
# ThingsBoard, Inc. ("COMPANY") CONFIDENTIAL
#
# Copyright Â© 2016-2025 ThingsBoard, Inc. All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains
# the property of ThingsBoard, Inc. and its suppliers,
# if any.  The intellectual and technical concepts contained
# herein are proprietary to ThingsBoard, Inc.
# and its suppliers and may be covered by U.S. and Foreign Patents,
# patents in process, and are protected by trade secret or copyright law.
#
# Dissemination of this information or reproduction of this material is strictly forbidden
# unless prior written permission is obtained from COMPANY.
#
# Access to the source code contained herein is hereby forbidden to anyone except current COMPANY employees,
# managers or contractors who have executed Confidentiality and Non-disclosure agreements
# explicitly covering such access.
#
# The copyright notice above does not evidence any actual or intended publication
# or disclosure  of  this source code, which includes
# information that is confidential and/or proprietary, and is a trade secret, of  COMPANY.
# ANY REPRODUCTION, MODIFICATION, DISTRIBUTION, PUBLIC  PERFORMANCE,
# OR PUBLIC DISPLAY OF OR THROUGH USE  OF THIS  SOURCE CODE  WITHOUT
# THE EXPRESS WRITTEN CONSENT OF COMPANY IS STRICTLY PROHIBITED,
# AND IN VIOLATION OF APPLICABLE LAWS AND INTERNATIONAL TREATIES.
# THE RECEIPT OR POSSESSION OF THIS SOURCE CODE AND/OR RELATED INFORMATION
# DOES NOT CONVEY OR IMPLY ANY RIGHTS TO REPRODUCE, DISCLOSE OR DISTRIBUTE ITS CONTENTS,
# OR TO MANUFACTURE, USE, OR SELL ANYTHING THAT IT  MAY DESCRIBE, IN WHOLE OR IN PART.
#

services:
  trendz:
    restart: always
    image: "${DOCKER_REPO}/${TRENDZ_DOCKER_NAME}:${TRENDZ_VERSION}"
    ports:
      - "8888"
    environment:
      SCRIPT_ENGINE_DOCKER_PROVIDER_URL: trendz-python-executor:8181
      JAVA_OPTS: "${JAVA_OPTS}"
    env_file:
      - ../trendz.env
    volumes:
      - ../trendz/conf:/trendz-config-files
      - ../trendz/log:/var/log/trendz
      - ../trendz/data:/data
    depends_on:
      - trendz-postgres
  trendz-python-executor:
    restart: always
    image: "${DOCKER_REPO}/${TRENDZ_PYTHON_EXECUTOR_DOCKER_NAME}:${TRENDZ_VERSION}"
    ports:
      - "8181"
    environment:
      JAVA_OPTS: "${JAVA_OPTS}"
    env_file:
      - ../trendz-python-executor.env
    volumes:
      - ../trendz-python-executor/conf:/python-executor-config-files
      - ../trendz-python-executor/log:/var/log/trendz
      - ../trendz-python-executor/data:/data
  trendz-postgres:
    restart: always
    image: "postgres:16"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: trendz
      POSTGRES_PASSWORD: postgres
    volumes:
      - ../trendz/postgres:/var/lib/postgresql/data
  tb-core1:
    env_file:
      - ../tb-node.trendz.env
    depends_on:
      - trendz
  tb-core2:
    env_file:
      - ../tb-node.trendz.env
    depends_on:
      - trendz
  haproxy:
    links:
      - trendz
