#
# ThingsBoard, Inc. ("COMPANY") CONFIDENTIAL
#
# Copyright Â© 2016-2019 ThingsBoard, Inc. All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains
# the property of ThingsBoard, Inc. and its suppliers,
# if any.  The intellectual and technical concepts contained
# herein are proprietary to ThingsBoard, Inc.
# and its suppliers and may be covered by U.S. and Foreign Patents,
# patents in process, and are protected by trade secret or copyright law.
#
# Dissemination of this information or reproduction of this material is strictly forbidden
# unless prior written permission is obtained from COMPANY.
#
# Access to the source code contained herein is hereby forbidden to anyone except current COMPANY employees,
# managers or contractors who have executed Confidentiality and Non-disclosure agreements
# explicitly covering such access.
#
# The copyright notice above does not evidence any actual or intended publication
# or disclosure  of  this source code, which includes
# information that is confidential and/or proprietary, and is a trade secret, of  COMPANY.
# ANY REPRODUCTION, MODIFICATION, DISTRIBUTION, PUBLIC  PERFORMANCE,
# OR PUBLIC DISPLAY OF OR THROUGH USE  OF THIS  SOURCE CODE  WITHOUT
# THE EXPRESS WRITTEN CONSENT OF COMPANY IS STRICTLY PROHIBITED,
# AND IN VIOLATION OF APPLICABLE LAWS AND INTERNATIONAL TREATIES.
# THE RECEIPT OR POSSESSION OF THIS SOURCE CODE AND/OR RELATED INFORMATION
# DOES NOT CONVEY OR IMPLY ANY RIGHTS TO REPRODUCE, DISCLOSE OR DISTRIBUTE ITS CONTENTS,
# OR TO MANUFACTURE, USE, OR SELL ANYTHING THAT IT  MAY DESCRIBE, IN WHOLE OR IN PART.
#

version: '3'

services:
  # Redis cluster
  redis-node-0:
    volumes:
      - redis-cluster-data-0:/bitnami/redis/data
  redis-node-1:
    volumes:
      - redis-cluster-data-1:/bitnami/redis/data
  redis-node-2:
    volumes:
      - redis-cluster-data-2:/bitnami/redis/data
  redis-node-3:
    volumes:
      - redis-cluster-data-3:/bitnami/redis/data
  redis-node-4:
    volumes:
      - redis-cluster-data-4:/bitnami/redis/data
  redis-node-5:
    volumes:
      - redis-cluster-data-5:/bitnami/redis/data

volumes:
  redis-cluster-data-0:
    external: true
    name: ${REDIS_CLUSTER_DATA_VOLUME_0}
  redis-cluster-data-1:
    external: true
    name: ${REDIS_CLUSTER_DATA_VOLUME_1}
  redis-cluster-data-2:
    external: true
    name: ${REDIS_CLUSTER_DATA_VOLUME_2}
  redis-cluster-data-3:
    external: true
    name: ${REDIS_CLUSTER_DATA_VOLUME_3}
  redis-cluster-data-4:
    external: true
    name: ${REDIS_CLUSTER_DATA_VOLUME_4}
  redis-cluster-data-5:
    external: true
    name: ${REDIS_CLUSTER_DATA_VOLUME_5}
